import { existsSync } from "node:fs";

import {
  ensureRuntimeDir,
  expandPath,
  loadSecretsEnv,
  loadUserConfig,
  systemEnvPath,
  systemYamlPath,
  dockerEnvPath,
  writeText,
} from "./paths.mjs";

function graphEnabled(cfg) {
  const neo = cfg.neo4j || {};
  if (neo.enabled === false) return false;
  if (neo.schema === "off") return false;
  return Boolean(neo.enabled);
}

function graphSchema(cfg) {
  const schema = String(cfg.neo4j?.schema || "sse").trim();
  return schema === "off" ? "sse" : schema;
}

export function validateUserConfig(cfg = loadUserConfig()) {
  const errors = [];
  const fastPath = expandPath(cfg.chroma?.fastqa?.vector_db_path || "");
  const thinkPath = expandPath(cfg.chroma?.thinking?.persist_dir || "");
  if (!fastPath) errors.push("chroma.fastqa.vector_db_path is required");
  else if (!existsSync(fastPath)) errors.push(`chroma.fastqa path not found: ${fastPath}`);
  if (!thinkPath) errors.push("chroma.thinking.persist_dir is required");
  else if (!existsSync(thinkPath)) errors.push(`chroma.thinking path not found: ${thinkPath}`);
  const secrets = loadSecretsEnv();
  if (!secrets.LLM_API_KEY && !secrets.DASHSCOPE_API_KEY) {
    errors.push("secrets.env missing LLM_API_KEY");
  }
  if (graphEnabled(cfg) && !secrets.NEO4J_PASSWORD && !secrets.FASTQA_NEO4J_PASSWORD) {
    errors.push("secrets.env missing NEO4J_PASSWORD (neo4j enabled)");
  }
  return { success: errors.length === 0, errors };
}

export function renderSystemYaml(cfg = loadUserConfig()) {
  const secrets = loadSecretsEnv();
  const llmKey = secrets.LLM_API_KEY || secrets.DASHSCOPE_API_KEY || "";
  const intentKey = secrets.INTENT_MODEL_API_KEY || llmKey;
  const embedKey =
    secrets.HIGHTHINKINGQA_EMBEDDING_API_KEY || secrets.EMBEDDING_API_KEY || llmKey;
  const neoPassword = secrets.NEO4J_PASSWORD || secrets.FASTQA_NEO4J_PASSWORD || "";
  const ports = cfg.ports || {};
  const fastPort = ports.fastqa || 18018;
  const thinkPort = ports.thinking || 18019;
  const redisPort = ports.redis || 16380;
  const enabledModes = String(cfg.modes?.enabled || "fast,thinking");
  const fastPath = expandPath(cfg.chroma?.fastqa?.vector_db_path || "");
  const fastMdPath = expandPath(cfg.chroma?.fastqa?.vector_db_md_path || `${fastPath}_md`);
  const thinkPath = expandPath(cfg.chroma?.thinking?.persist_dir || "");
  const collection = cfg.chroma?.thinking?.collection_name || "sse_literature";
  const llm = cfg.llm || {};
  const embedding = cfg.embedding || {};
  const embedType = embedding.type || "remote";
  const embedBase = embedding.base_url || llm.base_url || "https://dashscope.aliyuncs.com/compatible-mode/v1";
  const embedModel = embedding.model || "text-embedding-v4";
  const rerankProvider = cfg.rerank?.provider || "none";
  const graphOn = graphEnabled(cfg);
  const neo = cfg.neo4j || {};
  const neoUrl = neo.url || "bolt://127.0.0.1:7698";

  return `# generated by @sse-qa/cli — do not edit manually
agent:
  QA_SERVICES: "fastQA highThinkingQA"
  QA_ENABLED_MODES: ${enabledModes}
  QA_PATENT_ENABLED: 0
  SSE_QA_ENABLED_MODES: ${enabledModes}

_meta:
  stack: agent
  domain: solid_state_electrolyte

ports:
  FASTQA_PORT: ${fastPort}
  FASTQA_FASTAPI_PORT: ${fastPort}
  HIGHTHINKINGQA_PORT: ${thinkPort}
  PATENT_PORT: 18020

backends:
  FAST_BACKEND_BASE_URL: http://127.0.0.1:${fastPort}
  THINKING_BACKEND_BASE_URL: http://127.0.0.1:${thinkPort}
  PATENT_BACKEND_BASE_URL: http://127.0.0.1:18020

redis:
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: ${redisPort}
  REDIS_DB: 0
  REDIS_PASSWORD: "123456"
  REDIS_ENABLED: 1

storage:
  STORAGE_BACKEND: local
  LOCAL_STORAGE_ROOT: ${expandPath("~/.sse-qa/storage")}
  QA_ORIGINAL_MINIO_ONLY: false

neo4j:
  FASTQA_NEO4J_URL: ${neoUrl}
  FASTQA_NEO4J_USERNAME: ${neo.username || "neo4j"}
  FASTQA_NEO4J_PASSWORD: ${neoPassword}
  FASTQA_NEO4J_DATABASE: ${neo.database || "neo4j"}
  FASTQA_GRAPH_KB_ENABLED: ${graphOn ? 1 : 0}
  FASTQA_GRAPH_KB_SCHEMA: ${graphSchema(cfg)}
  FASTQA_GRAPH_KB_V2_ENABLED: ${graphOn ? 1 : 0}
  FASTQA_GRAPH_KB_RAG_INJECTION_ENABLED: ${graphOn ? 1 : 0}

llm:
  LLM_BASE_URL: ${llm.base_url || "https://dashscope.aliyuncs.com/compatible-mode/v1"}
  LLM_MODEL: ${llm.model || "qwen3.6-plus"}
  LLM_API_KEY: ${llmKey}
  LLM_IS_THINKING_MODEL: true
  LLM_THINKING_ENABLED: true

intent_model:
  INTENT_MODEL_ENABLED: true
  INTENT_MODEL_BASE_URL: ${llm.base_url || "https://dashscope.aliyuncs.com/compatible-mode/v1"}
  INTENT_MODEL: qwen3-8b
  INTENT_MODEL_API_KEY: ${intentKey}

embedding:
  EMBEDDING_BASE_URL: ${embedBase}/embeddings
  EMBEDDING_MODEL: ${embedModel}
  EMBEDDING_MODEL_TYPE: ${embedType}
  EMBEDDING_API_URL: ${embedBase}/embeddings
  HIGHTHINKINGQA_EMBEDDING_BASE_URL: ${embedBase}
  HIGHTHINKINGQA_EMBEDDING_MODEL: ${embedModel}
  HIGHTHINKINGQA_EMBEDDING_DIMENSIONS: 2048
  HIGHTHINKINGQA_EMBEDDING_API_KEY: ${embedKey}

rerank:
  RERANK_PROVIDER: ${rerankProvider}
  RERANK_BASE_URL: http://127.0.0.1:8084
  RERANK_MODEL: qwen3-vl-rerank

auth:
  QA_ANONYMOUS_ASK_ENABLED: 1
  HIGHTHINKINGQA_ANONYMOUS_ASK_ENABLED: 1

fastqa:
  FASTQA_GRAPH_KB_ENABLED: ${graphOn ? 1 : 0}
  FASTQA_GRAPH_KB_SCHEMA: ${graphSchema(cfg)}
  VECTOR_DB_PATH: ${fastPath}
  VECTOR_DB_MD_PATH: ${fastMdPath}
  FASTQA_PROMPTS_DIR: prompts

high_thinking:
  CHROMA_COLLECTION_NAME: ${collection}
  CHROMA_PERSIST_DIR: ${thinkPath}
  CONVERSATION_EXECUTION_AUTHORITY_TARGET: legacy
  CONVERSATION_ASSISTANT_WRITE_TARGET: legacy
  PROMPTS_DIR: prompts

patent:
  PATENT_SERVICE_ENABLED: 0
`;
}

function flattenYamlObject(obj, out = {}) {
  for (const [key, value] of Object.entries(obj || {})) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      flattenYamlObject(value, out);
    } else if (value !== null && value !== undefined && value !== "") {
      out[key] = String(value);
    }
  }
  return out;
}

export function renderSystemEnv(cfg = loadUserConfig()) {
  const yamlText = renderSystemYaml(cfg);
  const parsed = {};
  let section = parsed;
  const stack = [parsed];
  for (const line of yamlText.split(/\r?\n/)) {
    if (!line.trim() || line.trim().startsWith("#")) continue;
    const indent = line.match(/^ */)?.[0].length ?? 0;
    const content = line.trim();
    const colon = content.indexOf(":");
    if (colon <= 0) continue;
    const key = content.slice(0, colon).trim();
    const rest = content.slice(colon + 1).trim();
    while (stack.length > 1 && indent <= stack.length - 1) stack.pop();
    section = stack[stack.length - 1];
    if (!rest) {
      const child = {};
      section[key] = child;
      stack.push(child);
      continue;
    }
    section[key] = rest;
  }
  const flat = flattenYamlObject(parsed);
  const lines = Object.entries(flat)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `${k}=${v}`);
  return `${lines.join("\n")}\n`;
}

export function renderDockerEnv(cfg = loadUserConfig()) {
  const secrets = loadSecretsEnv();
  const fastPath = expandPath(cfg.chroma?.fastqa?.vector_db_path || "");
  const fastMdPath = expandPath(cfg.chroma?.fastqa?.vector_db_md_path || `${fastPath}_md`);
  const thinkPath = expandPath(cfg.chroma?.thinking?.persist_dir || "");
  const ports = cfg.ports || {};
  const lines = [
    `SSE_QA_VERSION=${process.env.SSE_QA_VERSION || "0.2.0"}`,
    `FASTQA_PORT=${ports.fastqa || 18018}`,
    `HIGHTHINKINGQA_PORT=${ports.thinking || 18019}`,
    `REDIS_PORT=${ports.redis || 16380}`,
    `CHROMA_FASTQA_HOST_PATH=${fastPath}`,
    `CHROMA_FASTQA_MD_HOST_PATH=${fastMdPath}`,
    `CHROMA_THINKING_HOST_PATH=${thinkPath}`,
    `LLM_API_KEY=${secrets.LLM_API_KEY || secrets.DASHSCOPE_API_KEY || ""}`,
    `INTENT_MODEL_API_KEY=${secrets.INTENT_MODEL_API_KEY || secrets.LLM_API_KEY || ""}`,
    `HIGHTHINKINGQA_EMBEDDING_API_KEY=${secrets.HIGHTHINKINGQA_EMBEDDING_API_KEY || secrets.LLM_API_KEY || ""}`,
    `EMBEDDING_API_KEY=${secrets.EMBEDDING_API_KEY || secrets.LLM_API_KEY || ""}`,
    `NEO4J_PASSWORD=${secrets.NEO4J_PASSWORD || secrets.FASTQA_NEO4J_PASSWORD || ""}`,
    `FASTQA_NEO4J_PASSWORD=${secrets.FASTQA_NEO4J_PASSWORD || secrets.NEO4J_PASSWORD || ""}`,
    `FASTQA_NEO4J_URL=${cfg.neo4j?.url || "bolt://host.docker.internal:7698"}`,
    `SSE_QA_CONFIG_HOME=${expandPath("~/.sse-qa")}`,
  ];
  return `${lines.join("\n")}\n`;
}

export function renderAllConfigs(cfg = loadUserConfig()) {
  ensureRuntimeDir();
  writeText(systemYamlPath(), renderSystemYaml(cfg));
  writeText(systemEnvPath(), renderSystemEnv(cfg));
  writeText(dockerEnvPath(), renderDockerEnv(cfg));
  return {
    systemYaml: systemYamlPath(),
    systemEnv: systemEnvPath(),
    dockerEnv: dockerEnvPath(),
  };
}
