#!/usr/bin/env bash
# Sync SSE_QA backend into packages/sse-qa-cli/runtime/backend for npm distribution.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$ROOT_DIR/packages/sse-qa-cli/runtime/backend"

echo "[sync] destination: $DEST"
rm -rf "$DEST"
mkdir -p "$DEST"

copy_tree() {
  local src="$1"
  local dst="$2"
  if [[ ! -d "$src" ]]; then
    echo "[sync] skip missing: $src"
    return 0
  fi
  mkdir -p "$(dirname "$dst")"
  rsync -a --delete \
    --exclude '.venv' \
    --exclude '__pycache__' \
    --exclude '.pytest_cache' \
    --exclude '.runtime' \
    --exclude 'node_modules' \
    --exclude 'tests' \
    "$src/" "$dst/"
  echo "[sync] copied $src -> $dst"
}

copy_tree "$ROOT_DIR/fastQA" "$DEST/fastQA"
copy_tree "$ROOT_DIR/highThinkingQA" "$DEST/highThinkingQA"

mkdir -p "$DEST/scripts" "$DEST/config" "$DEST/resource/config"
for script in start_all.sh stop_all.sh start_agent_all.sh stop_agent_all.sh \
  _service_common.sh render_system_config.py env_file_loader.sh; do
  cp "$ROOT_DIR/scripts/$script" "$DEST/scripts/"
done
chmod +x "$DEST/scripts/"*.sh 2>/dev/null || true

# Minimal config placeholders (runtime SYSTEM_YAML overrides)
cat > "$DEST/config/config.shared.env" <<'EOF'
# placeholder — overridden by ~/.sse-qa/runtime/system.agent.yaml
EOF
touch "$DEST/config/config.secret.env"

mkdir -p "$DEST/resource/config/shared" \
  "$DEST/resource/config/services/fastQA" "$DEST/resource/config/services/highThinkingQA" \
  "$DEST/resource/runtime/dev/fastQA" \
  "$DEST/resource/runtime/dev/highThinkingQA" "$DEST/resource/state/dev/fastQA" \
  "$DEST/resource/logs/dev/fastQA" \
  "$DEST/resource/logs/dev/highThinkingQA"

for f in infrastructure.shared.env model-endpoints.shared.env graph.shared.env \
  infrastructure.secret.env model-endpoints.secret.env graph.secret.env; do
  if [[ -f "$ROOT_DIR/resource/config/shared/$f" ]]; then
    cp "$ROOT_DIR/resource/config/shared/$f" "$DEST/resource/config/shared/"
  else
    touch "$DEST/resource/config/shared/$f"
  fi
done

for svc in fastQA highThinkingQA; do
  svc_dir="$ROOT_DIR/resource/config/services/$svc"
  if [[ -d "$svc_dir" ]]; then
    rsync -a "$svc_dir/" "$DEST/resource/config/services/$svc/"
  fi
done

# Merged Python requirements for native venv / Docker
REQ="$DEST/requirements.txt"
{
  echo "# generated by sync-server-bundle.sh"
  [[ -f "$ROOT_DIR/fastQA/pyproject.toml" ]] && sed -n '/dependencies = \[/,/^\]/p' "$ROOT_DIR/fastQA/pyproject.toml" | grep -E '^\s+"' | sed 's/^[[:space:]]*//; s/",$//; s/"//g'
  [[ -f "$ROOT_DIR/highThinkingQA/requirements.txt" ]] && cat "$ROOT_DIR/highThinkingQA/requirements.txt"
  echo "pyyaml>=6.0"
  echo "gunicorn>=21.2"
  echo "chromadb>=0.5.0"
  echo "neo4j>=5.0.0"
} | awk '!seen[$0]++' > "$REQ"

echo "[sync] wrote $REQ"
echo "[sync] done"
